---
- import_tasks: rhel_repo.yml
  when: ansible_os_family == "RedHat"

- import_tasks: ssl.yml
  when: rabbitmq_ssl_enabled | default(false)

- import_tasks: install.yml
- import_tasks: service.yml
- import_tasks: erlang_cookie.yml
- import_tasks: config.yml
- import_tasks: plugins.yml
- import_tasks: wait.yml
- import_tasks: users.yml
- import_tasks: cluster.yml
- import_tasks: ha_policy.yml
